### ISSUE TITLE
Question For "startFor"

### ISSUE THREAD

**Issue by Depth2World** [swabianinstruments/Time-Tagger-Custom-Measurements#2]
Hi there.

This is my code for the histogram counting.
####
histogram = TimeTagger.Histogram(tagger= self.tagger, # self.sync_tagger_proxy,
                                              click_channel=self.idq_channel,
                                              start_channel=self.laser_channel,
                                              # next_channel = self.laser_channel,
                                              binwidth=self.bin_width,
                                              n_bins=self.histo_length)

t1 = time.perf_counter()
histogram.startFor(1e9)
histogram.waitUntilFinished(timeout=-1)
print('time',time.perf_counter() - t1)
###
"startFor(1e9)" means the method will accumulates the histogram for 1e9ps (1ms).
However, the log prints "time 0.013s"， which is much larger than 1ms. 
I guess that "startFor(1e9)" contains many other commands which take most of the time.

And， how can I conduct a fast and accurate histogram accumulation?

**Comment by MircoSwabian** [comment]
Hi @Depth2World,
please send support requests like this one directly to support@swabianinstruments.com, this will make the support handling much more efficient. But, of course, I will answer your questions here directly:
The `startFor()` method controls the data processing directly on the time tag stream level. Your respective measurement object will receive a section of the data that represents exactly 1e9 ps. This processing is done in another thread and the execution order of data polling from hardware, execution of your commands, and processing by the measurement class is not fully defined. In your particular case, the execution time (1 ms) is much shorter than a typical USB block (~20-50 ms). So in general, the data transfer of the block might already be running or done when you call `startFor()`, which could even lead to an execution time shorter than 1 ms. In most cases you will observe some larger times like your 0.013 s because the measurement class needs to wait for the next USB data block. But what you can be sure about: With `startFor()`, you will exactly analyze 1e9 ps of your data. If you call `histogram.getCaptureDuration()` after the `waitUntilFinished()`, you will find that this is the exact result.
In this sense, the current execution is as fast and as accurate as it can be under the consideration of the latencies of the system. Using `startFor()` is definitely the right choice when it comes to accurate acquisition times.
I hope this answers your question,
best wishes,
Mirco
